patch: add  --skip-not-applicable-patches to  autoresolve not applicable patches
openSUSE/zypper pull request #532
Opened 2024-02-06 20:42 UTC by mlandres

(closes #514)
The first commits are fixes and enhancements to the patch. The last one introduces the feature.

If multiple problems are to be reported, zypper uses a 1st pass to quickly list all problems and a 2nd pass to ask to resolve each problem. 

We use the 1st pass to check for auto-applicable solutions and re-solve if solutions were applied. If problems still remain at the end, we ask.

The draft is basically ready. Remaining tasks:

- [ ] Remember skipped patches and show them in the summary.
- [ ] Upadte man page.

2024-02-07 10:59 UTC, mlandres commented
Screen output will look like this:
```
Resolving package dependencies...
2 Problems:
Problem: 1: the to be installed patch:openSUSE-SLE-15.4-2023-4534-1.noarch conflicts 
with 'zypper-aptitude < 1.14.66-150400.3.35.1' provided by the installed 
zypper-aptitude-1.14.61-150400.3.24.1.noarch
 Autoresolve:                                        (--skip-not-applicable-patches)
 Solution 1: Following actions will be done:
  do not install patch:openSUSE-SLE-15.4-2023-4534-1.noarch
  do not install patch:openSUSE-SLE-15.4-2023-3973-1.noarch
Problem: 2: the to be installed patch:openSUSE-SLE-15.4-2023-3514-1.noarch conflicts 
with 'zypper-aptitude < 1.14.63-150400.3.29.1' provided by the installed 
zypper-aptitude-1.14.61-150400.3.24.1.noarch
 Autoresolve:                                        (--skip-not-applicable-patches)
 Solution 1: Following actions will be done:
  do not install patch:openSUSE-SLE-15.4-2023-3514-1.noarch
  do not install patch:openSUSE-SLE-15.4-2023-3973-1.noarch

Resolving dependencies...
```

2024-02-22 08:05 UTC, bzeller requested changes

2024-02-22 08:05 UTC, bzeller commented on src/solve-commit.cc
> +              if ( not printAbsatract ) { // was not printed before
```suggestion
              if ( not printAbstract ) { // was not printed before
```

2024-02-22 08:05 UTC, bzeller commented on src/solve-commit.cc
> +                printAbsatract = false;
```suggestion
                printAbstract = false;
```

2024-02-22 08:29 UTC, mlandres commented on src/Summary.cc
> +void Summary::writeAutoResolved( std::ostream & out )
Well, ATM ist's just patches, but who knows. It's intended to be the hook for writing data from the summaryHints. Like the other writeSomething  methods it's not restricted to a specific Kind.

2024-02-22 08:39 UTC, mlandres commented on src/solve-commit.cc
> +            std::optional<std::set<PoolItem>> items { solPtr->getIfSkipsPatchesOnly() };
And if you look down the context, one more line you find the not-const usage in `merge`:
```policy.summaryHints.skippedPatchesSet().merge( *items );``` 
which could actually use `std:move( *items )`

2024-02-22 09:02 UTC, mlandres commented on src/solve-commit.cc
> +            std::optional<std::set<PoolItem>> items { solPtr->getIfSkipsPatchesOnly() };
281ff now:
```
              policy.summaryHints.skippedPatchesSet().merge( std::move(*items) );
              items.reset();  // moved out
```

2024-02-22 10:22 UTC, bzeller approved these changes

2024-02-22 14:01 UTC, merged